language: node_js
node_js:
- '8'
- '10'
deploy:
  provider: npm
  email:
    secure: dsBGPXl1VvR70rJ/UnRuaLwiesvmfxOSeWfuLOlWHU3+2uUA7xLOOIyjHxP3mlz9OLsL3A/tMsYBMj6bM3SrtvbtBwnAQZ+RKWjyIsiBTHYaIrXuJP+kbQIguaDTo8rC45U2VwZRQu50cc2Mln3jeGzlho4iPdZLe4rdRLnbAD0=
  api_key:
    secure: o0vLZpRdqWyu1Ez/x7Nug57uMOUahxpsKkEKNVk0AjIMPyc4lw1HaK9WRV0lm9F3R6kzBwxiUnfwvrcnmaEZRgnhcSF4WmqHtHB3u/lbNXTrJOWRnyjIESlA9IuIijbPZNKoRFac2DP3nHDcELKpGp0LeIFNZs47WvBM7dnDtdI=
  on:
    tags: true
    repo: getconversio/node-bigcommerce
notifications:
  slack:
    secure: fyAnH2j56FTfYCRCxhzDpuXKoBJ4DCNMPj7yCsCEr5gvQMl83Quzm+S6Kb+ORxxbvue9PpV0hyAmJlfRmNvYwj6Om0BneEKzKEj3/Useq8jMBzVDroe13s0nOIaAAHXYAfqJdgxNnzhep38WzIiFzS7StufGyYuxpka5ca6RCFQ=
